### ISSUE TITLE
General question regarding how to generate the spec file.

### ISSUE THREAD

**Issue by RainForestLand** [container-orchestrated-devices/container-device-interface#101]
Hello,

I am trying to use Nvidia gpus but I am still confused after going through the SPEC.md file.

I think we need to manually write a Json spec file as mentioned below in the doc

```
The device driver installation software writes a JSON file at a well known path (/etc/cdi/vendor.json).
```

As a new user, I not feeling intuitive for what values should I set for the SPEC json file. 

Is there a simple example for folks without much background context. Sorry for the trouble. 

Thanks

**Comment by kad** [comment]
For how it looks like in case of NVIDIA GPUs, you might have a look at complete solution (DRA driver for NVIDIA GPUs):
https://gitlab.com/nvidia/cloud-native/k8s-dra-driver

**Comment by RainForestLand** [comment]
> @RainForestLand NVIDIA is working on toolking to generation CDI specifications for NVIDA GPUs. This will be available with the next release of the [NVIDIA Container Toolkit](https://gitlab.com/nvidia/container-toolkit/container-toolkit). There should be a `v1.12.0-rc.2` release available by the end of the week that includes initial support for this.

Thanks @elezar! This is very promising. I'll just wait for some extra time for a standard release.
