### ISSUE TITLE
Failure when /etc/cdi dirs not present on the system but /var/run/cdi is

### ISSUE THREAD

**Issue by klueska** [container-orchestrated-devices/container-device-interface#115]
The default spec dirs are set set as follows:
```
cdi_spec_dirs = {
    /etc/cdi,
    /var/run/cdi,
}
```

If we are on a system that *only* has a `/var/run/cdi` directory (and not an `/etc/cdi` directory), then we fail to parse any of the cdi device files present in the `/var/run/cdi` directory.

Doing a simple `mkdir /etc/cdi` allows us to move past the error and find all of the devices in the `/var/run/cdi` directory.

**Comment by elezar** [comment]
I thought this was addressed? Which `crio` version was this?

**Comment by elezar** [comment]
cc @klihub

**Comment by elezar** [comment]
Git log shows it addressed in #79. Maybe there is still an issue.

**Comment by elezar** [comment]
The commit: https://github.com/container-orchestrated-devices/container-device-interface/pull/79/commits/e7cbe91de89de7db8ca3f8534b712d9f40323416 shows that this is in the following tags:

* [v0.5.4](https://github.com/container-orchestrated-devices/container-device-interface/releases/tag/v0.5.4)
* [v0.5.3](https://github.com/container-orchestrated-devices/container-device-interface/releases/tag/v0.5.3)
* [v0.5.2](https://github.com/container-orchestrated-devices/container-device-interface/releases/tag/v0.5.2)
* [v0.5.1](https://github.com/container-orchestrated-devices/container-device-interface/releases/tag/v0.5.1)

**Comment by klueska** [comment]
Ah, OK. We’ve already addressed it. Maybe it’s just still an issue in the the crio version used by minikube. cri-o version 1.24.1

This is the environmental observed it in.

**Comment by elezar** [comment]
`v1.24.1` of cri-o is using [v0.3.2](https://github.com/cri-o/cri-o/blob/v1.24.1/go.mod#L9) of the CDI package which does not include the fix.

**Comment by klueska** [comment]
I take it back -- it is using:
```
$ crio --version
crio version 1.24.4
```
but this is also on v0.3.2 of the CDI package:
https://github.com/cri-o/cri-o/blob/v1.24.4/go.mod#L9

which would explain the issue....
