### ISSUE TITLE
Allow for optional fields via "ignorable" X-prefixed

### ISSUE THREAD

**Issue by yarikoptic** [container-orchestrated-devices/container-device-interface#140]
There was a question on either spec could contain fields which are not part of the spec.  If someone really makes the case for adding them, might be worth to just allow for `X-` prefixed fields to be considered such, as is done since old times of https://www.rfc-editor.org/rfc/rfc822 for mail headers and then picked up by other standards (I believe .desktop files etc)

**Comment by elezar** [comment]
@yarikoptic could you give additional examples of such fields and what they would be used to achieve?

**Comment by yarikoptic** [comment]
well, we are talking about a JSON, so having something like `X-Description` since I cannot even add a comment comes immediately in mind to add some human readable detail.

`X-Version` comes to mind happen I decide to version my CDI specification for some reason outside of the VCS or may be even relying on some substitution variables etc.  Similarly to `X-Authors`, `X-Funding` etc  to provide more "credits" for some reason.  And so on.  

The point was - to allow for some flexibility while allowing for clear strict set of fields.

**Comment by elezar** [comment]
@yarikoptic as of the v0.6.0 specification, we do allow annotations at a spec and device level. Would these be sufficient for your specific use cases? Fields in the spec would ideally be tied to functionality, whereas annotations seem to better capture the metadata that you mention.

**Comment by yarikoptic** [comment]
I guess that is an alternative way -- schema less "annotations" field, eventually you might want to add it on top level too.  Anyways -- it was just an idea inspired by other (referenced) standards.
