### ISSUE TITLE
Tag v0.6.0

### ISSUE THREAD

**Issue by elezar** [container-orchestrated-devices/container-device-interface#147]
We should tag the v0.6.0 release.

This adds:
* CDI annotations
* Relaxes restrictions on the device class field
* Adds a separate `parse` package to reduce the dependencies for projects that only want to parse CDI device names.

This would clean up the integration with the Docker CLI, for example.

**Comment by elezar** [comment]
@bartosh @klihub @kad do you have any objections to me doing this while you're out?

**Comment by klihub** [comment]
@elezar I have no objections. Thanks for picking this up !

**Comment by elezar** [comment]
Thanks. I have published https://github.com/container-orchestrated-devices/container-device-interface/releases/tag/v0.6.0
