### ISSUE TITLE
uid and gid mappings missing

### ISSUE THREAD

**Issue by mythi** [container-orchestrated-devices/container-device-interface#17]
CDI should specify how non-root uid/gid are set for the devices.

**Comment by eero-t** [comment]
Otherwise Pods requesting devices need to run as root, which implies then having unnecessary access e.g. to device files in sysfs (which is mounted in its totality to containers).  I.e. this is a security issue.

**Comment by RenaudWasTaken** [comment]
This is a request that makes sense, do you want to make a PR for it?

**Comment by bart0sh** [comment]
I'd suggest to use the same approach as used in OCI runtime spec:
process/user contains the following fields:
- uid (int, REQUIRED) specifies the user ID in the container namespace.
- gid (int, REQUIRED) specifies the group ID in the container namespace.
- umask (int, OPTIONAL) specifies the [umask][umask_2] of the user. If unspecified, the umask should not be changed from the calling process' umask.
- additionalGids (array of ints, OPTIONAL) specifies additional group IDs in the container namespace to be added to the process.

if we want to cover Windows we can add username field:
- username (string, OPTIONAL) specifies the user name for the process

So, in CDI spec it would looks something like this:
```
"ociEdits": {
    "user": [
      {"uid": 1000, "gid": 1000}
    ],
```

@mythi @eero-t  would this cover your uid/gid requirements?

**Comment by eero-t** [comment]
@bart0sh it's not clear to me from your comment context, is your suggestion for CDI internal API, or what user requesting a device will specify.  Latter is what this ticket is about, but "ociEdits" sounds more like former.  Could you clarify?

**Comment by bart0sh** [comment]
It was a suggestion to use set of user related parameters from OCI runtime spec in the CDI spec.
I'm not sure I've answered your question though. Can you clarify?

**Comment by RenaudWasTaken** [comment]
Cc @mrunalp @mikebrow want to have more input on this

**Comment by RenaudWasTaken** [comment]
PR #27 just got merged - closing this
