### ISSUE TITLE
Environment Variable setup

### ISSUE THREAD

**Issue by RenaudWasTaken** [container-orchestrated-devices/container-device-interface#20]
What: The spec currently does not have the ability to edit the environment variables
Fix: Add Environment variables to the spec and the `ApplyEditsToOCISpec` function

**Comment by bart0sh** [comment]
@RenaudWasTaken @kad Please review #21

**Comment by kad** [comment]
@bart0sh as #19 and #21  are now merged, can you add one more PR to implement `env` inject into ApplyOCIEdits?
