### ISSUE TITLE
CDI spec doesn't provide enough info about devices

### ISSUE THREAD

**Issue by bart0sh** [container-orchestrated-devices/container-device-interface#26]
CDI spec doesn't have the following device properties that present in the [OCI Linux.Devices spec](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#Devices):
- device type
- major
- minor
- fileMode
- uid
- gid

And doesn't target Linux.Devices at all in its current implementation.

**Comment by bart0sh** [comment]
@RenaudWasTaken @mrunalp To address this issue we should add missing properties to the DeviceNode and use them to populate Linux.Devices in OCI config. Does this make sense to you?

**Comment by RenaudWasTaken** [comment]
> @RenaudWasTaken @mrunalp To address this issue we should add missing properties to the DeviceNode and use them to populate Linux.Devices in OCI config. Does this make sense to you?

Completely, I was looking through some of our discussions to understand why we weren't going down that route  :D !

**Comment by RenaudWasTaken** [comment]
We can do that :) !

**Comment by elezar** [comment]
@bart0sh as mentioned in the meeting today, when I was experimenting with direct OCI modifications to get Devices working, I needed access to the device major / minor numbers to update the cgroups in the `LinuxResources`.

There are also devices (e.g. MIG devices) for which the device nodes may not exist on the host.
