### ISSUE TITLE
Change the "permissions" field of the deviceNodes Structure

### ISSUE THREAD

**Issue by RenaudWasTaken** [container-orchestrated-devices/container-device-interface#29]
From https://github.com/container-orchestrated-devices/container-device-interface/pull/27, we decided to use the OCI structure https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#devices

For which a field `fileMode` is defined instead of the CRI `permissions` field:
```
fileMode (uint32, OPTIONAL) - file mode for the device. You can also control access to devices with cgroups.
```

**Comment by RenaudWasTaken** [comment]
cc @bart0sh

**Comment by bart0sh** [comment]
@RenaudWasTaken @kad There are two ways to specify access to devices in the OCI spec. One is similar to CDI "permissions": https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#configLinuxDeviceAllowedlist
and another is to use "fileMode": https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#devices

From this perspective it doesn't make much sense to drop "permissions" in favor of "fileMode" in my opinion.
Should we consider using both or just keep using "permissions"?
