### ISSUE TITLE
Please do not use init functions in library code

### ISSUE THREAD

**Issue by Luap99** [container-orchestrated-devices/container-device-interface#61]
When updating container-device-interface from 0.3.0 to 0.3.1 we see a over 500 KB binary size increase in podman, https://github.com/containers/podman/pull/13610
However podman uses only small parts of the code in pkg/cdi, such size increase does not seem reasonable to me. Podman does not use any new logic.
Unless I am overlooking something the problem seems to be caused by https://github.com/container-orchestrated-devices/container-device-interface/pull/54
The use of init functions has two major problems: 
 - First, it always runs on program startup so this slow each podman command down, even when most code paths will never even call CDI.

- Second, it adds a lot unnecessary binary size because it calls code that way never be used otherwise by the library user. This is made worse by the fact that the PR started to embed the json spec into the binary.

I don't have enough knowledge about how this library is used to suggest a good fix.

**Comment by elezar** [comment]
Thanks for bringing this to our attention @Luap99.

@klihub could you have a look at this?

**Comment by klihub** [comment]
@elezar @Luap99 I'll take a look at getting rid of it.

**Comment by Luap99** [comment]
Thanks for the quick fix.
