### ISSUE TITLE
there is a data race in CDI version v0.5.0

### ISSUE THREAD

**Issue by soulseen** [container-orchestrated-devices/container-device-interface#81]
related PR: https://github.com/containerd/containerd/pull/7331
this PR stuck with a data race when I wanted to update the CDI version to v0.5.0 in contained.
I suspect there is a data race error here but I can't be sure:
1. https://github.com/container-orchestrated-devices/container-device-interface/blob/main/pkg/cdi/cache.go#L449
2. https://github.com/container-orchestrated-devices/container-device-interface/blob/main/pkg/cdi/cache.go#L436

**Comment by elezar** [comment]
@klihub could you have a look at this?
