### ISSUE TITLE
Remove dependency on github.com/pkg/errors

### ISSUE THREAD

**Issue by alculquicondor** [container-orchestrated-devices/container-device-interface#90]
IIUC, the functionality it provides is now available in the builtin libraries.

**Comment by pohly** [comment]
I agree, that makes sense.

However, this is less urgent than https://github.com/container-orchestrated-devices/container-device-interface/issues/88 because Kubernetes already vendors github.com/pkg/errors.

**Comment by alculquicondor** [comment]
Good point: kubernetes/kubernetes#113627

**Comment by klihub** [comment]
#99 eliminates all usage of `github.com/pkg/errors`.

**Comment by elezar** [comment]
Closing this as #99 has been merged.
