### ISSUE TITLE
CDI file versioning

### ISSUE THREAD

**Issue by pohly** [container-orchestrated-devices/container-device-interface#91]
After updating to 0.5.3, I generated CDI files with version CurrentVersion = cdi.CurrentVersion = 0.5.0.

Those files where not accepted by crio 1.24.2.

It started working again after switching back to 0.2.0.

What is the right version to use with the current CDI 0.5.3 package?

**Comment by klihub** [comment]
CRI-O has not been updated with latest CDI. I'll file a PR.

**Comment by elezar** [comment]
@klihub which version is CRI-O currently on? It should be at least 0.3.0 since this was our first tagged version.

**Comment by klihub** [comment]
I just checked (original comment was inaccurate). master/main is on `0.5.2`.

**Comment by klihub** [comment]
In hindsight, the suggestion to use `cdi.CurrentVersion` in generated Specs was not necessarily the best idea. If we soon stop bumping the version then it'll probably be fine. If not, then maybe it would be better to
- define also an `EarliestCompatibleVersion`
- update the docs to suggest using that by default, unless newer features are really used
- ensure during Spec write that the advertised version is in sync with the Spec content

**Comment by elezar** [comment]
I don't know whether we can set this value statically. Would it be possible to add a `minVersion` tag to the spec fields and then query this using the `reflect` package to get the minimum required version for the spec being saved?

We would then check all the non-empty fields of the spec for the highest `minVersion` and use this when creating the spec. This need not be automatic, but we should provide utility functions that could check this as a start.

**Comment by elezar** [comment]
I have created https://github.com/container-orchestrated-devices/container-device-interface/pull/93 to take a pass at this. I'm not sure whether where I'm putting this is best. I can see methods off each of the spec types that returns the minimum version (or the empty string in cases where it doesn't matter), but 'm not sure whether that complicates our API.

**Comment by elezar** [comment]
Note that I have removed the requirement for creating a spec with the minimal version of the spec automatically. This requires a bit of a rework on how the spec is validated. I can add it if we think that this is a requirement.
